// Generated by https://quicktype.io

export interface ClienteDatos {
    pageNumber: number;
    pageSize:   number;
    succeeded:  boolean;
    message:    null;
    errors:     null;
    data:       Cliente[];
}

export interface Cliente {
    clienteId:     string;
    cedulaCliente: number;
    nombre:        string;
    apellido:      string;
    direccion:     string;
    telefono:      string;
}
