// Generated by https://quicktype.io

export interface RespuestaDetalleProducto {
  factura: Factura[];
  detalleFacturaProducto: DetalleFacturaProducto[];
}

export interface DetalleFacturaProducto {
  detalleFacturaProductoId: string;
  codigo: string;
  producto: Producto;
  productoId: string;
  cantidad: number;
  valorUnitario: number;
  valorTotal: number;
}

export interface Producto {
  productoId: string;
  nombre: string;
  descripcion: string;
  precioCompra: number;
  stock: number;
  precioVentaCliente: number;
  categoriaProducto: null;
  categoriaProductoId: string;
}

export interface Factura {
  facturaId: string;
  fechaFactura: string;
  codigo: string;
  cliente: null;
  clienteId: string;
  totalProductosVenta: number;
  valorTotalVenta: number;
}
